<?php

namespace Database\Seeders;

use App\Models\Order;
use App\Models\Product;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        if (Order::exists()) {
            return;
        }

        $products = Product::where('is_available', true)->limit(4)->get();

        if ($products->isEmpty()) {
            return;
        }

        foreach ([
            ['Guest 001', 'pending', 'unpaid'],
            ['Guest 002', 'preparing', 'paid'],
            ['Guest 003', 'ready', 'paid'],
            ['Guest 004', 'completed', 'paid'],
        ] as [$customer, $status, $paymentStatus]) {
            $selected = $products->random(min(2, $products->count()));
            $subtotal = 0;

            $order = Order::create([
                'order_number' => Order::generateOrderNumber(),
                'customer_name' => $customer,
                'order_type' => 'kiosk',
                'payment_method' => 'mock',
                'payment_status' => $paymentStatus,
                'status' => $status,
                'subtotal_amount' => 0,
                'discount_amount' => 0,
                'total_amount' => 0,
                'notes' => 'Demo order generated by seeder.',
            ]);

            foreach ($selected as $product) {
                $quantity = rand(1, 3);
                $lineTotal = (float) $product->price * $quantity;
                $subtotal += $lineTotal;

                $order->items()->create([
                    'product_id' => $product->id,
                    'product_name' => $product->name,
                    'price' => $product->price,
                    'quantity' => $quantity,
                    'subtotal' => $lineTotal,
                ]);
            }

            $order->update([
                'subtotal_amount' => $subtotal,
                'total_amount' => $subtotal,
            ]);
        }
    }
}
